import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.dirname(fileURLToPath(import.meta.url));
const reportDir=path.resolve(root,'../review');await mkdir(path.join(reportDir,'screenshots'),{recursive:true});
const server=spawn('python3',[path.join(root,'server.py'),'--port','47832'],{stdio:['ignore','pipe','pipe']});
await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);server.once('exit',code=>reject(Error('preview server exited '+code)));});
const browser=await chromium.launch({headless:true,...(process.env.CHROME_EXECUTABLE?{executablePath:process.env.CHROME_EXECUTABLE}:process.platform==='darwin'?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{})});
const context=await browser.newContext({viewport:{width:1440,height:900},acceptDownloads:true});const p=await context.newPage();const errors=[];p.on('pageerror',e=>errors.push(String(e)));const checks=[];
const check=(name)=>{checks.push(name);console.log('PASS',name);};
const log=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('discuss-lab-v1')));
const lastSeq=async()=>(await log()).at(-1).seq;
async function selectText(text){await p.locator('#documentText').evaluate((el,text)=>{const full=el.textContent,start=full.indexOf(text);if(start<0)throw Error('quote missing');const w=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let node,offset=0,a,b;while(node=w.nextNode()){if(!a&&offset+node.length>start)a=[node,start-offset];if(offset+node.length>=start+text.length){b=[node,start+text.length-offset];break;}offset+=node.length;}const range=document.createRange();range.setStart(...a);range.setEnd(...b);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);el.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));},text);await p.locator('#selectionButton').click();}
try{
 await p.goto('http://127.0.0.1:47832/prototype/');await p.locator('#documentText').waitFor();assert.equal(await p.locator('.comment').count(),2);await p.screenshot({path:path.join(reportDir,'screenshots/prototype-desktop.png'),fullPage:true});check('Initial document, anchored seed discussion and visible stub label');
 await selectText('Комментарии и снимки храним рядом с документом или в общем локальном хранилище.');await p.locator('#commentInput').fill('@codex/architect Как переносить историю?');await p.locator('#sendButton').click();await p.waitForFunction(()=>document.querySelector('#threadPanel').textContent.includes('демонстрационный ответ architect'));let es=await log();let request=es.findLast(e=>e.type==='agent.requested').payload;assert.equal(request.agent,'@codex/architect');assert.equal(es.findLast(e=>e.type==='comment.created').payload.snapshotId,request.snapshotId);check('Real text selection → new thread → mentioned specialist stub → anchored reply');
 await p.locator('.comment').last().getByRole('button',{name:'Ответить',exact:true}).click();assert.match(await p.locator('#composerHint').innerText(),/автоматически/);await p.locator('#commentInput').fill('Уточни, как работает экспорт.');await p.locator('#sendButton').click();await p.waitForFunction(()=>document.querySelectorAll('.comment').length===4);assert.equal((await log()).filter(e=>e.type==='agent.requested').length,2);check('Human reply to agent automatically continues the conversation without another @');
 const oldThread=request.threadId;await p.locator('.comment').first().getByRole('button',{name:'↗ Ветка',exact:true}).click();await p.locator('#commentInput').fill('Отдельно обсудим резервную копию.');await p.locator('#sendButton').click();es=await log();const fork=es.findLast(e=>e.type==='thread.forked').payload;assert.notEqual(fork.id,oldThread);assert.ok(fork.forkedFromCommentId);await p.getByRole('button',{name:'✓ Решить',exact:true}).click();assert.match(await p.locator('#threadPanel').innerText(),/Решено/);await p.getByRole('button',{name:'Открыть снова',exact:true}).click();check('Independent branch, origin link, resolve and reopen');
 const react=p.locator('[data-react][data-emoji="💡"]').first();await react.click();assert.equal(await p.locator('[data-react][data-emoji="💡"]').first().getAttribute('aria-pressed'),'true');await p.locator('[data-react][data-emoji="💡"]').first().click();assert.equal(await p.locator('[data-react][data-emoji="💡"]').first().getAttribute('aria-pressed'),'false');check('Reaction add/remove persists as separate events');
 const beforeChange=await lastSeq();await p.locator('#changeButton').click();assert.match(await p.locator('#versionBanner').innerText(),/новая версия/);await p.getByRole('button',{name:'Открыть новую',exact:true}).click();assert.match(await p.locator('#documentText').innerText(),/at-least-once/);assert.equal(await p.locator('#documentText mark').count(),0);await p.getByRole('button',{name:'Открыть контекст ↗',exact:true}).click();assert.match(await p.locator('#documentText').innerText(),/ровно один раз/);check('External edit creates S2; old anchor retains S1 and opens original context');
 await p.getByRole('button',{name:'История',exact:true}).click();await p.locator('#timeSlider').fill('4');await p.locator('#timeSlider').dispatchEvent('input');assert.equal(await p.locator('#commentInput').isDisabled(),true);await p.getByRole('button',{name:'Все треды',exact:true}).click();await p.locator('[data-thread="t1"]').click();assert.equal(await p.locator('.comment').count(),1);assert.equal(await p.locator('#versionSelect').isDisabled(),true);await p.getByRole('button',{name:'Вернуться в настоящее',exact:true}).click();assert.equal(await p.locator('#commentInput').isDisabled(),false);check('as-of restores only past comments and locks mutations/version selector; return to live');
 await p.getByRole('button',{name:'События',exact:false}).first().click();await p.locator('#subscriptionToggle').click();const cursor=await p.locator('#cursorLabel').innerText();await p.locator('#commentInput').fill('Комментарий во время паузы подписки.');await p.locator('#sendButton').click();assert.equal(await p.locator('#cursorLabel').innerText(),cursor);assert.match(await p.locator('#eventsBadge').innerText(),/\+/);await p.locator('#subscriptionToggle').click();assert.equal(await p.locator('#eventsBadge').innerText(),'');await p.locator('#eventFilter').selectOption('comment');assert.ok((await p.locator('#eventList summary').allTextContents()).every(x=>x.includes('comment.')));check('Paused event subscription holds cursor, catches up, and filters events');
 await p.locator('#agentToggle').click();await p.locator('#commentInput').fill('@claude/reviewer Проверь после подключения.');await p.locator('#sendButton').click();assert.match(await p.locator('#threadPanel').innerText(),/нет соединения/);const offlineCount=(await log()).filter(e=>e.type==='comment.created').length;await p.waitForTimeout(2400);assert.equal((await log()).filter(e=>e.type==='comment.created').length,offlineCount);await p.locator('#agentToggle').click();await p.waitForFunction(()=>!document.querySelector('.agent-status'));check('Disconnected agent request waits and resumes exactly one stub response');
 await p.locator('#storageButton').click();await p.locator('[data-store="sidecar"]').click();assert.match(await p.locator('#storageButton').innerText(),/В папке документа/);check('Sidecar preference is explicit and labeled as simulated storage');
 const downloadPromise=p.waitForEvent('download');await p.locator('#exportButton').click();const download=await downloadPromise;const archivePath=path.join(reportDir,'browser-export.json');await download.saveAs(archivePath);const archived=JSON.parse(await readFile(archivePath,'utf8'));assert.ok(archived.events.some(e=>e.type==='snapshot.captured'));await p.locator('#importInput').setInputFiles(archivePath);await p.locator('#confirmImport').click();assert.deepEqual(await log(),archived.events);await p.reload();assert.deepEqual(await log(),archived.events);check('Downloaded archive restores snapshots/events and survives a browser reload');
 await p.locator('#fileInput').setInputFiles({name:'заметка с пробелом.txt',mimeType:'text/plain',buffer:Buffer.from('🙂 первая мысль\r\n🙂 вторая мысль')});await p.waitForFunction(()=>document.querySelector('#docName').textContent==='заметка с пробелом.txt');await p.getByRole('button',{name:'Текст',exact:true}).click();await selectText('🙂 вторая мысль');await p.locator('#commentInput').fill('Комментарий к Unicode.');await p.locator('#sendButton').click();es=await log();const created=es.findLast(e=>e.type==='thread.created').payload;const snapshot=es.find(e=>e.type==='snapshot.captured'&&e.payload.id===created.snapshotId).payload;assert.equal(Array.from(snapshot.text).slice(created.start,created.end).join(''),created.quote);check('Actual UTF-8 file input, Unicode filename, emoji and CRLF selection');
 await selectText('🙂 первая мысль\r\n🙂 вторая мысль');await p.locator('#commentInput').fill('Второе выделение при подсвеченном треде.');await p.locator('#sendButton').click();es=await log();const crlfThread=es.findLast(e=>e.type==='thread.created').payload;assert.equal(crlfThread.quote,'🙂 первая мысль\r\n🙂 вторая мысль');assert.equal(crlfThread.start,0);assert.equal(await p.locator('#documentText').textContent(),'🙂 первая мысль\r\n🙂 вторая мысль');await p.reload();assert.deepEqual(await log(),es);check('CRLF second selection across newline with existing highlight and reload preserves full journal');

 await p.locator('#openButton').click();await p.locator('[data-modal="finder"]').click();await p.locator('[data-modal="entry-finder"]').click();assert.equal(await p.locator('#docName').innerText(),'proposal.md');await p.locator('#openButton').click();await p.locator('[data-modal="terminal"]').click();await p.locator('[data-modal="entry-terminal"]').click();assert.equal((await log()).filter(e=>e.type==='document.opened'&&e.payload.id==='doc-demo').length,1);check('Finder and CLI simulations reopen the same document without duplicate identity');
 await p.locator('[data-thread="t1"]').click();await p.locator('#labButton').click();await p.locator('[data-modal="fallback"]').click();await p.locator('#commentInput').fill('@claude/reviewer Проверим fallback.');await p.locator('#sendButton').click();await p.waitForFunction(()=>document.querySelector('#threadPanel').textContent.includes('Родитель ответил сам'));assert.match(await p.locator('#threadPanel').innerText(),/parent fallback · специалист не вызван · demo/);assert.ok((await log()).some(e=>e.type==='agent.status'&&e.payload.receipt==='parent-fallback'));await p.locator('#labButton').click();await p.locator('[data-modal="fallback"]').click();check('Native child receipts and parent fallback are distinct in the visible UX and journal');
 await p.locator('#commentInput').fill('@codex/architect Запрос с разрывом после receipt.');await p.locator('#sendButton').click();await p.waitForFunction(()=>JSON.parse(localStorage.getItem('discuss-lab-v1')).at(-1).payload.status==='parent-accepted');await p.locator('#agentToggle').click();assert.match(await p.locator('.agent-status').innerText(),/исход доставки неизвестен/);const unknownCount=(await log()).filter(e=>e.type==='comment.created').length;await p.locator('#agentToggle').click();await p.waitForTimeout(3000);assert.equal((await log()).filter(e=>e.type==='comment.created').length,unknownCount);await p.locator('[data-retry]').click();await p.locator('[data-confirm-retry]').click();await p.waitForFunction(()=>!document.querySelector('.agent-status'));assert.equal((await log()).filter(e=>e.type==='comment.created').length,unknownCount+1);check('Disconnect after parent receipt becomes unknown and requires explicit retry with duplicate-risk explanation');
 await p.locator('#commentInput').fill('@claude/reviewer Перезагрузка после receipt.');await p.locator('#sendButton').click();await p.waitForFunction(()=>JSON.parse(localStorage.getItem('discuss-lab-v1')).at(-1).payload.status==='parent-accepted');await p.reload();assert.equal((await log()).at(-1).payload.status,'delivery-unknown');await p.locator('[data-cancel-request]').click();check('Reload reconciles accepted request to unknown rather than silently retrying');
 await p.locator('#agentToggle').click();await p.locator('#commentInput').fill('@claude/reviewer Неотправленная очередь после перезагрузки.');await p.locator('#sendButton').click();const queuedId=(await log()).findLast(e=>e.type==='agent.requested').payload.id;await p.reload();await p.waitForFunction(id=>JSON.parse(localStorage.getItem('discuss-lab-v1')).some(e=>e.type==='agent.status'&&e.payload.id===id&&e.payload.status==='completed'),queuedId);assert.equal((await log()).filter(e=>e.type==='comment.created'&&e.payload.requestId===queuedId).length,1);check('Unsent queued request resumes once after reload, unlike acknowledged work');
 const intact=JSON.stringify(await log());await p.evaluate(()=>localStorage.setItem('discuss-lab-v1','{broken archive'));await p.reload();assert.match(await p.locator('#recoveryBanner').innerText(),/Оригинал сохранён/);assert.equal(await p.evaluate(()=>localStorage.getItem('discuss-lab-v1')),'{broken archive');assert.equal(await p.evaluate(()=>Object.keys(localStorage).some(k=>k.startsWith('discuss-lab-v1-recovery-')&&localStorage.getItem(k)==='{broken archive')),true);await p.evaluate(raw=>localStorage.setItem('discuss-lab-v1',raw),intact);await p.reload();check('Invalid stored history is backed up, exposed in recovery banner, and never overwritten by seed');

 await p.setViewportSize({width:390,height:844});await p.screenshot({path:path.join(reportDir,'screenshots/prototype-mobile.png'),fullPage:true});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.locator('#labButton').click();assert.equal(await p.locator('#modal').isVisible(),true);assert.equal(await p.locator('[data-modal="export"]').isVisible(),true);assert.equal(await p.locator('[data-modal="import"]').isVisible(),true);await p.locator('#closeModal').click();check('390px layout has no horizontal overflow and demo controls remain accessible');
 await p.setViewportSize({width:1440,height:1000});await p.goto('http://127.0.0.1:47832/architecture.html');await p.locator('[data-step="3"]').click();assert.match(await p.locator('#sceneMode').innerText(),/as-of/);await p.screenshot({path:path.join(reportDir,'screenshots/architecture-light.png'),fullPage:true});await p.locator('#theme').click();assert.equal(await p.locator('body').getAttribute('class'),'dark');await p.screenshot({path:path.join(reportDir,'screenshots/architecture-dark.png'),fullPage:true});assert.equal(await p.locator('svg').count(),1);check('Self-contained architecture scene switching, SVG, light and dark render');
 assert.deepEqual(errors,[]);check('No browser page errors across the exercised paths');
 await writeFile(path.join(reportDir,'browser-results.json'),JSON.stringify({at:new Date().toISOString(),browser:await browser.version(),viewport:[1440,900],mobile:[390,844],passed:checks.length,checks,errors},null,2));
}catch(e){await p.screenshot({path:path.join(reportDir,'screenshots/failure.png'),fullPage:true});throw e;}
finally{await browser.close();server.kill();}
