import test from 'node:test';
import assert from 'node:assert/strict';
import {append,project,seed,validateArchive} from './domain.mjs';
test('replay excludes future comments and reactions without modifying the log',()=>{const e=seed(),original=structuredClone(e);const s=project(e,4);assert.deepEqual(Object.keys(s.comments),['c1']);assert.equal(Object.keys(s.reactions).length,0);assert.equal(Object.keys(project(e).comments).length,2);assert.deepEqual(e,original);});
test('resolve/reopen and reaction removal remain visible at historical cutoffs',()=>{let e=seed();e=append(e,'thread.resolved',{threadId:'t1'});const cutoff=e.at(-1).seq;e=append(e,'thread.reopened',{threadId:'t1'});e=append(e,'reaction.set',{commentId:'c2',actor:'Камиль',emoji:'👍',active:false});assert.equal(project(e,cutoff).threads.t1.resolved,true);assert.equal(project(e).threads.t1.resolved,false);assert.equal(Object.keys(project(e).reactions).length,0);assert.equal(Object.keys(project(e,cutoff).reactions).length,1);});
test('new snapshot leaves original anchor and comment context intact',()=>{let e=seed();e=append(e,'snapshot.captured',{id:'s2',documentId:'doc-demo',label:'S2',text:'Другой текст'});const s=project(e);assert.equal(s.documents['doc-demo'].head,'s2');assert.equal(s.threads.t1.snapshotId,'s1');assert.equal(s.comments.c2.snapshotId,'s1');assert.equal(project(e,6).documents['doc-demo'].head,'s1');});
test('fork has independent resolution and preserves origin',()=>{let e=seed();const t=project(e).threads.t1;e=append(e,'thread.forked',{...t,id:'t2',forkedFromCommentId:'c2'});e=append(e,'thread.resolved',{threadId:'t2'});const s=project(e);assert.equal(s.threads.t1.resolved,false);assert.equal(s.threads.t2.resolved,true);assert.equal(s.threads.t2.forkedFromCommentId,'c2');});
test('repeated command is idempotent and mismatching retry is rejected',()=>{let e=seed();e=append(e,'thread.resolved',{threadId:'t1'},'Камиль','command-1');assert.equal(append(e,'thread.resolved',{threadId:'t1'},'Камиль','command-1'),e);assert.throws(()=>append(e,'thread.resolved',{threadId:'t2'},'Камиль','command-1'));});
test('archive round trip reproduces state and rejects duplicate event IDs',()=>{const e=seed();const restored=validateArchive(JSON.parse(JSON.stringify({format:'discuss-demo/1',events:e})));assert.deepEqual(project(restored),project(e));const broken=structuredClone(e);broken[1].eventId=broken[0].eventId;assert.throws(()=>validateArchive({format:'discuss-demo/1',events:broken}));});
test('archive rejects wrong quote and broken parent references',()=>{for(const mutate of [e=>e[2].payload.quote='неверная цитата',e=>e[4].payload.parentId='missing',e=>e[4].payload.parentId='c2']){const e=seed();mutate(e);assert.throws(()=>validateArchive({format:'discuss-demo/1',events:e}));}});
test('code point anchors preserve emoji, CRLF and repeated quote positions',()=>{let e=[];const text='🙂 мысль\r\n🙂 мысль';e=append(e,'document.opened',{id:'d',name:'unicode.txt'});e=append(e,'snapshot.captured',{id:'s',documentId:'d',text,label:'S1'});const start=9,end=16;assert.equal(Array.from(text).slice(start,end).join(''),'🙂 мысль');e=append(e,'thread.created',{id:'t',documentId:'d',snapshotId:'s',start,end,quote:'🙂 мысль'});assert.equal(validateArchive({format:'discuss-demo/1',events:e}).length,3);});

test('archive rejects untrusted agent status and nonnumeric context bound',()=>{for(const payload of [{id:'r',status:'<img src=x onerror=alert(1)>'},{id:'r',status:'running',throughSeq:'<b>42</b>'}]){let e=seed();e=append(e,'agent.status',payload);assert.throws(()=>validateArchive({format:'discuss-demo/1',events:e}));}});
test('folder storage preference applies to existing and later documents in that folder',()=>{let e=seed();e=append(e,'storage.selected',{documentId:'doc-demo',folderId:'demo-documents',mode:'sidecar'});e=append(e,'document.opened',{id:'second',folderId:'demo-documents',name:'second.txt',storage:'central'});const s=project(e);assert.equal(s.documents['doc-demo'].storage,'sidecar');assert.equal(s.documents.second.storage,'sidecar');});

test('archive rejects nonstring response requestId before rendering',()=>{const e=seed();e[4].payload.requestId=42;assert.throws(()=>validateArchive({format:'discuss-demo/1',events:e}));});
